### PR TITLE
chore: make wasm32-wasi default target

### PR DESCRIPTION
**Pull request by sunng87**
Add `.cargo` configuration to make `wasm32-wasi` default target when user run `cargo build`.

### CODE REVIEW

**Comment by juntao** [comment]
Thanks! Can you remove the `lock` file from the PR?

**Comment by sunng87** [comment]
No problem. But this lock file is neither up to date/included in repo/ingored, I think we need to change something at least.

**Comment by sunng87** [comment]
The CI failure seems to be unrelated with this PR

**Comment by juntao** [comment]
Yeah, the PR CI has no access to the repo secret value.

> The CI failure seems to be unrelated with this PR

**Review by juntao — APPROVED** [review]

**Pull request merged**
