### PR TITLE
feat: add greptimedb example

### LINKED ISSUE #15: Suggestion for adding GreptimeDB example?
I was trying to add an example for using mysql_async client to connect to GreptimeDB instance on cloud. Currently there are two blocking issues that I cannot just simply reuse the `crud.wasm` example:

- We require a timestamp index column in the table so the current `orders` table doesn't match, it results in a create table error
- In order to workaround a Grafana bug, we now set MySQL protocol TLS mode to `preferred`, while with mysql_async, it assumes server to be `required` https://github.com/blackbeam/mysql_async/issues/225#issuecomment-1409922237. So until Grafana has fixed their issue, we cannot use TLS in this example.

A simple proposal can be adding a new file and binary target in `mysql_async` module of this project, named as `greptimedb.rs`, as an example of connecting to greptimedb using wasmedge+mysql_async. Just to confirm if this will work for you.

### PR DESCRIPTION
**Pull request by sunng87**
Fixes #15

This patch adds example for creating table, ingesting and querying data against greptimedb, using wasmedge.

### CODE REVIEW

**Review by juntao — COMMENTED** [review]
Great! Thanks! Can you also add a CI task on GitHub Actions? You could install greptimedb in the script and then start it as a server like we did for MySQL.

**Comment by sunng87** [comment]
CI task added. The test should pass when new nightly build of greptimedb is out on next monday. I will rerun the test then.

**Comment by sunng87** [comment]
@juntao The CI now works for greptimedb

**Review by juntao — APPROVED** [review]
Thank you so much!

**Pull request merged**
